parameters:
  - name: ServiceConnection
    type: string

  - name: TerraformCodeLocation
    type: string

  - name: TerraformWorkspace
    type: string

  - name: TerraformInitExtraArgsJson
    type: string


jobs:
  - template: ./terraform-init-plan-destroy.yaml
    parameters:
      TerraformCodeLocation: ${{ parameters.TerraformCodeLocation }}
      TerraformWorkspace: ${{ parameters.TerraformWorkspace }}
      ServiceConnection: ${{ parameters.ServiceConnection }}
      TerraformInitExtraArgsJson: ${{ parameters.TerraformInitExtraArgsJson }}

  - template: ./terraform-manual-approval.yaml
    parameters:
      DependsOnJobs: [TerraformInitPlanDestroyJob]

  - template: ./terraform-init-destroy.yaml
    parameters:
      TerraformCodeLocation: ${{ parameters.TerraformCodeLocation }}
      TerraformWorkspace: ${{ parameters.TerraformWorkspace }}
      ServiceConnection: ${{ parameters.ServiceConnection }}
      TerraformInitExtraArgsJson: ${{ parameters.TerraformInitExtraArgsJson }}
      DependsOnJobs: [ManualApprovalJob]
