parameters:
  - name: JobName
    type: string
    default: ManualApprovalJob
    displayName: 'Custom Job Name'

  - name: JobDisplayName
    type: string
    default: "Manual Approval for Terraform"
    displayName: 'Custom Job Display Name'

  - name: NotifyUsers
    type: string
    displayName: 'Notify Users'
    default: ''

  - name: Instructions
    type: string
    default: 'Review the Terraform plan before applying.'
    displayName: 'Instructions'

  - name: TimeoutInMinutes
    type: string
    default: '60'
    displayName: 'Timeout in Minutes'

  - name: OnTimeout
    type: string
    default: 'reject'
    displayName: 'On Timeout'

  - name: dependsOnJobs
    type: object
    default: []
    displayName: 'Depends On'

jobs:
  - job: ${{ parameters.JobName }}
    displayName: ${{ parameters.JobDisplayName }}
    dependsOn: ${{ parameters.dependsOnJobs }}
    pool: server  # This runs on the server, not on an agent
    steps:
      - task: ManualValidation@0
        inputs:
          notifyUsers: ${{ parameters.NotifyUsers }}
          instructions: ${{ parameters.Instructions }}
          timeoutInMinutes: ${{ parameters.TimeoutInMinutes }}
          onTimeout: ${{ parameters.OnTimeout }}
        displayName: 'Manual Approval to Apply Terraform Changes'