parameters:
  - name: StageName
    type: string
    default: TerraformFreeFormStage
    displayName: 'Custom Stage Name'

  - name: StageDisplayName
    type: string
    default: "Terraform Free Form Commands"
    displayName: 'Custom Stage Display Name'

  - name: JobName
    type: string
    default: TerraformFreeFormJob
    displayName: 'Custom Job Name'

  - name: JobDisplayName
    type: string
    default: "Terraform Free Form Commands"
    displayName: 'Custom Job Display Name'

  - name: TerraformCodeLocation
    type: string
    default: 'terraform'
    displayName: 'Terraform Code Path'

  - name: TerraformArguments
    type: string
    default: ''
    displayName: Run Terraform free form commands

  - name: DebugMode
    type: string
    values: [ "true", "false" ]
    default: "false"
    displayName: 'Enable Debug Logging'

  - name: UseAzureClientSecretLogin
    type: string
    values: [ "true", "false" ]
    default: "false"
    displayName: 'Use Azure Client Secret Login'

  - name: UseAzureOidcLogin
    type: string
    values: [ "true", "false" ]
    default: "true"
    displayName: 'Use Azure OIDC Login'

  - name: UseAzureUserLogin
    type: string
    values: [ "true", "false" ]
    default: "false"
    displayName: 'Use Azure User (Device Code) Login'

  - name: UseAzureManagedIdentityLogin
    type: string
    values: [ "true", "false" ]
    default: "false"
    displayName: 'Use Azure Managed Identity Login'

  - name: UseAzureServiceConnection
    type: string
    values: [ "true", "false" ]
    default: "true"
    displayName: 'Use Azure DevOps Service Connection'

  - name: ServiceConnection
    type: string
    displayName: 'Azure DevOps Service Connection Name'

  - name: additionalEnvVars
    type: object
    default: { }
    displayName: 'Additional Environment Variables to Export'

  - name: additionalJobVars
    type: object
    default: { }
    displayName: 'Additional Job Variables'

  - name: additionalStageVars
    type: object
    default: { }
    displayName: 'Additional Stage Variables'

  - name: BackendUseAzureADAuth
    type: string
    values: [ "true", "false" ]
    default: "true"
    displayName: 'Backend Authentication via Azure AD'

  - name: TargetSubscriptionId
    type: string
    default: ''
    displayName: 'Target Azure Subscription ID (Overrides Default)'

  - name: AzureDevOpsPoolName
    type: string
    default: ''
    displayName: 'The Pool Name for the Job to run on'

  - name: AzurePipelinesVmImage
    type: string
    default: 'ubuntu-latest'
    displayName: 'If Azure Pipelines is selected, which vmImage to run'

  - name: dependsOnJobs
    displayName: "Depends On"
    type: object
    default: [ ]

  - name: dependsOnStages
    displayName: "Depends On"
    type: object
    default: [ ]

  - name: WorkspaceClean
    displayName: "Workspace clean"
    type: string
    default: "all"
    values:
      - "all"
      - "outputs"
      - "resources"

  - name: EnableGitLongPaths
    values: [ "true", "false" ]
    default: "true"
    displayName: 'Run Git Long paths enablement'

  - name: ConfigureAzureDevOpsGitUrl
    values: [ "true", "false" ]
    default: "false"
    displayName: 'Configure the Git Azure DevOps URL with insteadof for System.AccessToken injection'

stages:
  - stage: ${{ parameters.StageName }}
    displayName: ${{ parameters.StageDisplayName }}
    dependsOn: ${{ parameters.dependsOnStages }}
    ${{ if ne(length(parameters.additionalStageVars), 0) }}:
      variables:
        ${{ each stageVar in parameters.additionalStageVars }}:
          ${{ stageVar.Key }}: ${{ stageVar.Value }}
    jobs:
      - job: ${{ parameters.JobName }}
        displayName: ${{ parameters.JobDisplayName }}
        pool:
          name: ${{ parameters.AzureDevOpsPoolName }}
          ${{ if eq(parameters.AzureDevOpsPoolName, 'Azure Pipelines') }}:
            vmImage: ${{ parameters.AzurePipelinesVmImage }}
        dependsOn: ${{ parameters.dependsOnJobs }}
        workspace:
          clean: ${{ parameters.WorkspaceClean }}

        ${{ if ne(length(parameters.additionalJobVars), 0) }}:
          variables:
            ${{ each jobVar in parameters.additionalJobVars }}:
              ${{ jobVar.Key }}: ${{ jobVar.Value }}

        steps:
          - template: ../steps/terraform-free-form.yaml
            parameters:
              TerraformCodeLocation: ${{ parameters.TerraformCodeLocation }}
              TerraformArguments: ${{ parameters.TerraformArguments }}
              DebugMode: ${{ parameters.DebugMode }}
              UseAzureClientSecretLogin: ${{ parameters.UseAzureClientSecretLogin }}
              UseAzureOidcLogin: ${{ parameters.UseAzureOidcLogin }}
              UseAzureUserLogin: ${{ parameters.UseAzureUserLogin }}
              UseAzureManagedIdentityLogin: ${{ parameters.UseAzureManagedIdentityLogin }}
              UseAzureServiceConnection: ${{ parameters.UseAzureServiceConnection }}
              ServiceConnection: ${{ parameters.ServiceConnection }}
              additionalEnvVars: ${{ parameters.additionalEnvVars }}
              BackendUseAzureADAuth: ${{ parameters.BackendUseAzureADAuth }}
              TargetSubscriptionId: ${{ parameters.TargetSubscriptionId }}
              EnableGitLongPaths: ${{ parameters.EnableGitLongPaths }}
              ConfigureAzureDevOpsGitUrl: ${{ parameters.ConfigureAzureDevOpsGitUrl }}