name: terraform-init-plan.yaml-$(Build.DefinitionName)-$(date:yyyyMMdd)$(rev:.r)

trigger: none

parameters:
  - name: ServiceConnection
    type: string
    default: "spn-libd-uks-dev-mgmt-01"
    displayName: 'Azure DevOps Service Connection'
    values:
      - "spn-libd-uks-dev-mgmt-01-client-secret-enabled"
      - "spn-libd-uks-dev-mgmt-01"
      - "uid-libd-uks-dev-mgmt-01"

  - name: TerraformCodeLocation
    type: string
    default: '$(Build.SourcesDirectory)/terraform/0_rg'
    displayName: 'Terraform Code Directory Path'

  - name: TerraformWorkspace
    type: string
    default: 'dev'
    displayName: 'Terraform Workspace Name'

  - name: TerraformInitExtraArgsJson
    type: string
    default: >
      [
        "-backend-config=subscription_id=$(TF_VAR_ARM_BACKEND_SUBSCRIPTION_ID)",
        "-backend-config=resource_group_name=$(TF_VAR_ARM_BACKEND_STORAGE_RG_NAME)",
        "-backend-config=storage_account_name=$(TF_VAR_ARM_BACKEND_STORAGE_ACCOUNT)",
        "-backend-config=container_name=$(TF_VAR_ARM_BACKEND_CONTAINER_NAME)"
      ]
    displayName: 'Extra Args for terraform init'

resources:
  repositories:
    - repository: templates
      type: git
      name: libre-devops-terraform-modules/terraform-templates
      ref: main

pool: 'Default'

variables:
  - group: terraform-${{ parameters.TerraformWorkspace }}-vars

steps:
  - template: .azurepipelines/templates/steps/terraform-install.yaml@templates

  - template: .azurepipelines/templates/steps/terraform-init.yaml@templates
    parameters:
      TerraformCodeLocation: ${{ parameters.TerraformCodeLocation }}
      TerraformInitExtraArgsJson: ${{ parameters.TerraformInitExtraArgsJson }}
      ServiceConnection: ${{ parameters.ServiceConnection }}
      TerraformWorkspace: ${{ parameters.TerraformWorkspace }}

  - template: .azurepipelines/templates/steps/terraform-plan-destroy.yaml@templates
    parameters:
      TerraformCodeLocation: ${{ parameters.TerraformCodeLocation }}

  - template: .azurepipelines/templates/steps/terraform-destroy.yaml@templates
    parameters:
      TerraformCodeLocation: ${{ parameters.TerraformCodeLocation }}
